# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160420_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 4, 20, 4, 7, 33, 783076, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
